# Generated by Django 2.0.3 on 2018-04-23 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('paid', 'Pago'), ('pending', 'Pendiente')], default='paid', max_length=30)),
                ('registration_date', models.DateField()),
                ('registration_upto', models.DateField()),
                ('name', models.CharField(help_text='Nombre del gimnasio', max_length=100)),
                ('address', models.CharField(help_text='Dirección', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GymActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Nombre', max_length=50)),
                ('last_name', models.CharField(help_text='Apellido', max_length=50)),
                ('cellphone', models.CharField(help_text='Teléfono Celular', max_length=50)),
                ('address', models.CharField(help_text='Dirección', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('emergency_contact', models.CharField(blank=True, help_text='Teéfono de contacto en caso de emergencia', max_length=50, null=True)),
                ('batch', models.CharField(choices=[('morning', 'Mañana'), ('evening', 'Tarde'), ('night', 'Noche'), ('full', 'Fulltime')], default='morning', help_text='Turno', max_length=30)),
                ('photo', models.FileField(blank=True, help_text='Foto', null=True, upload_to='photos/')),
                ('medical_certificate', models.FileField(blank=True, help_text='Certificado médico', null=True, upload_to='medical_certificate/')),
                ('gym', models.ForeignKey(help_text='Miembro del gimnasio', on_delete=django.db.models.deletion.CASCADE, to='members.Gym')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Nombre', max_length=50)),
                ('last_name', models.CharField(help_text='Apellido', max_length=50)),
                ('cellphone', models.CharField(help_text='Teléfono Celular', max_length=50)),
                ('address', models.CharField(help_text='Dirección', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('is_owner', models.NullBooleanField()),
                ('gym', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Gym')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
