# Generated by Django 2.0.3 on 2018-04-21 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(unique=True)),
                ('emerency_contact', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('admitted_on', models.DateField(auto_now_add=True)),
                ('registration_date', models.DateField()),
                ('registration_upto', models.DateField()),
                ('subscription_period', models.CharField(choices=[('1', '1 Month'), ('3', '3 Months'), ('6', '6 Months'), ('12', '12 Months')], default='1', max_length=30)),
                ('account_status', models.CharField(choices=[('paid', 'Pago'), ('pending', 'Pendiente')], default='paid', max_length=30)),
                ('batch', models.CharField(choices=[('morning', 'Mañana'), ('evening', 'Tarde'), ('night', 'Noche'), ('full', 'Fulltime')], default='morning', max_length=30)),
                ('photo', models.FileField(blank=True, upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='subscription_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Subscription'),
        ),
    ]
