# Generated by Django 2.0.4 on 2018-04-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='dni',
            field=models.CharField(default=33000000, max_length=9, unique=True),
            preserve_default=False,
        ),
    ]
