# Generated by Django 2.0.3 on 2018-04-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('paid', 'Pago'), ('pending', 'Pendiente')], default='paid', max_length=30)),
                ('registration_date', models.DateField()),
                ('registration_upto', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='member',
            old_name='account_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='member',
            name='admitted_on',
        ),
    ]
